### ISSUE TITLE
Fails on Windows 11 system DLLs (shell32.dll, imageres.dll, etc)

### ISSUE THREAD

**Issue by bmrussell** [jlu5/icoextract#18]
```
PS C:\> icolist -v C:\Windows\System32\wpdshext.dll
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "H:\Code\github\lgbatpy\.venv\Scripts\icolist.exe\__main__.py", line 7, in <module>
  File "H:\Code\github\lgbatpy\.venv\Lib\site-packages\icoextract\scripts\icolist.py", line 20, in main
    extractor = IconExtractor(args.input)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Code\github\lgbatpy\.venv\Lib\site-packages\icoextract\__init__.py", line 56, in __init__
    raise NoIconsAvailableError("File has no group icon resources")
icoextract.NoIconsAvailableError: File has no group icon resources
```

**Comment by jlu5** [comment]
Please see the [note in the README](https://github.com/jlu5/icoextract#usage):

> Note: recent versions of Windows (Windows 10 1903+) have moved icons from system libraries (shell32.dll, etc.) into a new [C:\Windows\SystemResources](https://superuser.com/questions/1480268/) folder. icoextract can extract these .mun files natively, but the .dlls themselves no longer contain icons.
